variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 100
  PKG_VER: 0.0.0

include:
  - local: /.gitlab/build-astra.yml
    rules:
    - if: $CI_PIPELINE_SOURCE == "trigger-install-windows"
      when: never
    - when: always
  - local: /.gitlab/build-windows.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "trigger-install-alse"
        when: never
      - when: always

  - local: /.gitlab/install.yml
  - local: /.gitlab/doxygen.yml

stages:
  - build
  - install
  - documentation
