variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 100
  PKG_VER: 0.0.0

include:
  - local: /.gitlab/build-astra.yml
  - local: /.gitlab/build-windows.yml
  - local: /.gitlab/install.yml
  - local: /.gitlab/doxygen.yml

stages:
  - build
  - install
  - documentation
