[package]
name = "leafconf"
version = "0.1.3"
authors = ["whs31 <whs31@github.io>"]
description = "Configuration/serialization library for C++ projects"

[dependencies]
cmake = { version = "0.1.2", distribution = "sources" }
leaf = { version = "0.4.1", distribution = "static" }
toml = { version = "3.4.0", distribution = "static" }
