[package]
name = "leafconf"
authors = ["whs31 <whs31@github.io>"]
description = "Configuration/serialization library for C++ projects"

[package.version]
major = 0
minor = 1
patch = 2

[dependencies]
cmake = { version = { major = 0, minor = 1, patch = 2 }, distribution = "sources" }
leaf = { version = { major = 0, minor = 3, patch = 4 }, distribution = "static" }
toml = { version = { major = 3, minor = 4, patch = 0 }, distribution = "static" }
